### PR TITLE
Update dependency: Update level version

### PR DESCRIPTION
**Pull request by jrbenito**
Some other packages are now depending on Level 1.4.x and this package
conflicts with them. However this package can be used with level 1.4 as
well.

Signed-off-by: Josenivaldo Benito Jr jrbenito@benito.qsl.br

### CODE REVIEW

**Comment by jrbenito** [comment]
@andreialecu ,

Any thoughts?

**Comment by jrbenito** [comment]
Thanks a lot @andreialecu

**Comment by andreialecu** [comment]
Sorry for the delay, I missed the intial notification.

**Comment by jrbenito** [comment]
No problem man! Thanks again.

**Comment by andreialecu** [comment]
I published the new version to npm too.

**Pull request merged**
